kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: docker:dind
    volumes:
      - name: docker
        path: /var/run/docker.sock
      - name: pegaz
        path: /opt/pegaz
    environment:
      CI_DOMAIN:
        from_secret: CI_DOMAIN
    commands:
      - apk add --upgrade bash sed
      - source /opt/pegaz/config.sh
      - adduser -D $USERNAME
      - WORKDIR="/opt/pegaz/services/$DRONE_REPO_NAME"
      - rm -rf $WORKDIR
      - su $USERNAME -c "mkdir $WORKDIR"
      - su $USERNAME -c "rsync -av --exclude  ./node_modules /drone/src/ $WORKDIR"
      - cd $WORKDIR
      - bash /opt/pegaz/cli.pegaz.sh up $DRONE_REPO_NAME

volumes:
  - name: pegaz
    host:
      path: /opt/pegaz
  - name: docker
    host:
      path: /var/run/docker.sock
