kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: docker:dind
    volumes:
      - name: docker
        path: /var/run/docker.sock
      - name: dockerweb
        path: ~/docker-web
    environment:
      CI_DOMAIN:
        from_secret: CI_DOMAIN
    commands:
      - apk add --upgrade npm bash findutils rsync sed
      - source ~/docker-web/config.sh
      - adduser -D $USERNAME
      - WORKDIR="~/docker-web/services/$DRONE_REPO_NAME"
      - rm -rf $WORKDIR
      - su $USERNAME -c "mkdir $WORKDIR"
      - su $USERNAME -c "rsync -av --exclude  ./node_modules /drone/src/ $WORKDIR"
      - cd $WORKDIR
      - npm install
      - [[ -f config.sh ]] && sed -i "s|DOMAIN=.*|DOMAIN=\"$CI_DOMAIN\"|g" config.sh
      - [[ -f .env ]] && sed -i "s|DOMAIN=.*|DOMAIN=\"$CI_DOMAIN\"|g" .env
      - bash ~/docker-web/src/cli.sh up $DRONE_REPO_NAME

volumes:
  - name: dockerweb
    host:
      path: ~/docker-web
  - name: docker
    host:
      path: /var/run/docker.sock
