services:

  code:
    image: linuxserver/code-server
    container_name: code
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
     - config:/config
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PASSWORD: "${PASSWORD}"
      SUDO_PASSWORD: "${PASSWORD}"
      PROXY_DOMAIN: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

volumes:
  config:

networks:
  default:
    name: pegaz
    external: true