version: "3.7"

services:

  nextcloud:
    container_name: nextcloud
    image: nextcloud/all-in-one
    ports:
      - ${PORT}:80
    environment:
      VIRTUAL_HOST:     "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_HOST: "${SUBDOMAIN}.${DOMAIN}"
      PHP_MEMORY_LIMIT: 4G
      PHP_UPLOAD_LIMIT: 16G
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
    depends_on:
      - nextcloud_db
    links:
      - nextcloud_db
    volumes:
      - html:/var/www/html
      - ${PATH_MEDIA}:/var/www/media
  nextcloud_db:
    container_name: nextcloud_db
    image: postgres:14
    ports:
      - ${PORT_DB}:5432
    restart: always
    volumes:
      - ${PATH_DATA}/nextcloud/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASS}

volumes:
  html:

networks:
  default:
    external: true
    name: pegaz
