kind: pipeline
type: docker
name: default

steps:
- name: deploy
  image: docker:dind
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: pegaz
    path: /opt/pegaz
  environment:
    CI_DOMAIN:
      from_secret: CI_DOMAIN
  commands:
    - apk add --upgrade npm bash findutils rsync sed
    - WORKDIR="/opt/pegaz/services/soulseek"
    - rm -rf $WORKDIR
    - mkdir $WORKDIR
    - rsync -av --progress ./ $WORKDIR --exclude ./node_modules
    - cd $WORKDIR
    - npm install
    - [[ -f config.sh ]] && sed -i "s|DOMAIN=.*|DOMAIN=\"$CI_DOMAIN\"|g" config.sh
    - [[ -f .env ]] && sed -i "s|DOMAIN=.*|DOMAIN=\"$CI_DOMAIN\"|g" .env
    - bash /opt/pegaz/cli.pegaz.sh up soulseek

volumes:
- name: pegaz
  host:
    path: /opt/pegaz
- name: docker
  host:
    path: /var/run/docker.sock
