services:
  drone:
    image: drone/drone:2.24
    container_name: drone
    restart: unless-stopped
    dns:
     - 8.8.8.8
     - gitea
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - $PORT:80
    volumes:
      - data:/data
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      DRONE_AGENTS_ENABLED: "true"
      DRONE_TLS_AUTOCERT: "false"
      DRONE_OPEN: "false"
      DRONE_GIT_ALWAYS_AUTH: "false"
      DRONE_GITEA_SERVER: "${PROTO}://${DOMAIN_GITEA}"
      DRONE_GITEA_CLIENT_ID: "${GITEA_CLIENT_ID}"
      DRONE_GITEA_CLIENT_SECRET: "${GITEA_CLIENT_SECRET}"
      DRONE_RPC_SECRET: "${RPC_SECRET}"
      DRONE_SERVER_HOST: "${DOMAIN}"
      DRONE_SERVER_PROTO: "${PROTO}"
      DRONE_USER_CREATE: "username:${USERNAME},email:${EMAIL},password:${PASSWORD},admin:true"

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DRONE_RPC_HOST: "${DOMAIN}"
      DRONE_RPC_PROTO: "${PROTO}"
      DRONE_RPC_SECRET: "${RPC_SECRET}"
      DRONE_RUNNER_CAPACITY: "4"
      DRONE_RUNNER_NAME: "runner-docker"
      DRONE_RUNNER_NETWORKS: "dockerweb"
      DRONE_RUNNER_VOLUMES: "$PATH_DOCKERWEB:$PATH_DOCKERWEB"

volumes:
  data:

networks:
  default:
    name: dockerweb
    external: true
