#!/bin/bash
set -e

source src/env.sh

OLD_VERSION=$DOCKERWEB_VERSION
OLD_MONTH=$(echo $OLD_VERSION | cut -d'.' -f2)
NEW_VERSION=$(echo $OLD_VERSION | cut -d'.' -f3)
NEW_YEAR=$(date +%y)
NEW_MONTH=$(date +%m | sed 's/^0//')

[[ $NEW_MONTH > $OLD_MONTH ]] && NEW_VERSION=1 || ((NEW_VERSION++))

NEW_FULL_VERSION="$NEW_YEAR.$NEW_MONTH.$NEW_VERSION"

sed -i "s|DOCKERWEB_VERSION=.*|DOCKERWEB_VERSION=\"$NEW_FULL_VERSION\"|g" src/env.sh
git add src/env.sh
git tag $NEW_FULL_VERSION
git push origin --tags
