#!/bin/bash
set -e

source src/env.sh

OLD_MONTH=$(echo $DOCKERWEB_VERSION | cut -d'.' -f2)
VERSION=$(echo $DOCKERWEB_VERSION | cut -d'.' -f3)
NEW_YEAR=$(date +%y)
NEW_MONTH=$(date +%m | sed 's/^0//')

[[ $NEW_MONTH > $OLD_MONTH ]] && VERSION=1 || ((VERSION++))

NEW_FULL_VERSION="$NEW_YEAR.$NEW_MONTH.$VERSION"

sed -i "s|DOCKERWEB_VERSION=.*|DOCKERWEB_VERSION=\"$NEW_FULL_VERSION\"|g" src/env.sh
git add src/env.sh
git tag $NEW_FULL_VERSION
git push origin --tags

# Update store

ARCHIVE_DIR="store/_archives"
INDEX_FILE="${ARCHIVE_DIR}/index.json"

mkdir -p "$ARCHIVE_DIR"

echo "{" > "$INDEX_FILE"
echo '  "apps": [' >> "$INDEX_FILE"

first=1

for APP in store/*; do
  [[ ! -d "$APP" || "$APP" == "store/_archives" ]] && continue
  NAME=$(basename "$APP")
  ENV_FILE="$APP/$FILENAME_ENV"

  PORT=0
  if [[ -f "$ENV_FILE" ]]; then
    # Search for PORT in env.sh
    PORT=$(sed -n 's/^export PORT="\([^"]*\)"/\1/p' "$ENV_FILE")
    [[ -z "$PORT" ]] && PORT=$(sed -n 's/^PORT="\([^"]*\)"/\1/p' "$ENV_FILE")
    if ! [[ $PORT =~ ^[0-9]+$ ]]; then
      PORT=0
    fi
  fi

  # Generate archive
  ARCHIVE="$ARCHIVE_DIR/${NAME}.tar.gz"
  tar --exclude='node_modules' --exclude='.nuxt' -czf "$ARCHIVE" -C store "$NAME"

  # Add comma if not first entry
  [ $first -eq 0 ] && echo "," >> "$INDEX_FILE"
  first=0

  cat >> "$INDEX_FILE" <<EOF
    {
      "name": "$NAME",
      "url": "https://raw.githubusercontent.com/docker-web/docker-web/main/store/$ARCHIVE",
      "port": $PORT
    }
EOF

done

echo "  ]" >> "$INDEX_FILE"
echo "}" >> "$INDEX_FILE"

git add "$ARCHIVE_DIR"
git add "$INDEX_FILE"

echo "[docker-web store] archives et index.json mis à jour avec ports depuis env.sh"
