version: "3.7"
services:
  drone:
    image: hoppscotch/hoppscotch:latest
    container_name: hoppscotch
    restart: unless-stopped
    ports:
      - $PORT:3000
    volumes:
      - app:/app
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"

volumes:
  app:

networks:
  default:
    name: pegaz
