services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - config:/config
      - cache:/cache
      - $MEDIA_DIR:/media
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      JELLYFIN_PublishedServerUrl: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

  dizquetv:
    image: vexorian/dizquetv
    ports:
      - 7713:8000
      - 7714:8001
    volumes:
      - ./dizquetv:/home/node/app/.dizquetv
    depends_on:
      - jellyfin
    restart: unless-stopped

volumes:
  config:
  cache:

networks:
  default:
    name: dockerweb
    external: true
