version: "3.7"
services:

  penpot:
    image: penpotapp/frontend:latest
    container_name: penpot
    depends_on:
    - penpot-backend
    - penpot-exporter
    ports:
    - ${PORT}:80
    volumes:
    - assets:/opt/data/assets
    environment:
      VIRTUAL_HOST: "${SUBDOMAIN}.${DOMAIN}"
      VIRTUAL_PORT: "${PORT}"
      LETSENCRYPT_HOST: "${SUBDOMAIN}.${DOMAIN}"
      PENPOT_PUBLIC_URI: "${SUBDOMAIN}.${DOMAIN}"
      PENPOT_TENANT: "pro"
      PENPOT_HTTP_SERVER_HOST: "0.0.0.0"

  penpot-backend:
    image: penpotapp/backend:latest
    container_name: penpot-backend
    depends_on:
      - penpot-postgres
      - penpot-redis
    volumes:
    - assets:/opt/penpot/backend/assets
    environment:
      PENPOT_DATABASE_URI: "postgresql://penpot-postgres/penpot"
      PENPOT_DATABASE_USERNAME: "penpot"
      PENPOT_DATABASE_PASSWORD: "penpot"
      PENPOT_REDIS_URI: "redis://penpot-redis/0"
      PENPOT_ASSETS_STORAGE_BACKEND: "assets-fs"
      PENPOT_STORAGE_ASSETS_FS_DIRECTORY: "/opt/data/assets"
      PENPOT_TELEMETRY_ENABLED: "false"
      PENPOT_SMTP_ENABLED: "false"
      PENPOT_SMTP_DEFAULT_FROM: "${EMAIL}"
      PENPOT_SMTP_DEFAULT_REPLY_TO: "${EMAIL}"
      PENPOT_FLAGS: "${PENPOT_FLAGS} disable-registration"

  penpot-exporter:
    image: penpotapp/exporter:latest
    container_name: penpot-exporter
    environment:
      PENPOT_PUBLIC_URI: "http://penpot"

  penpot-postgres:
    image: postgres:alpine
    container_name: penpot-postgres
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_DB: "penpot"
      POSTGRES_USER: "penpot"
      POSTGRES_PASSWORD: "penpot"

  penpot-redis:
    image: redis:alpine
    container_name: penpot-redis
    restart: unless-stopped

volumes:
  db:
  assets:

networks:
  default:
    external:
      name: pegaz
