services:
  azuracast:
    image: azuracast/azuracast
    container_name: azuracast
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - "${MEDIA_DIR}:/mnt/media"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      AZURACAST_DC_REVISION: "latest"
    volumes:
      - data:/var/azuracast

volumes:
  data:

networks:
  default:
    name: dockerweb
    external: true
