version: "3.7"
services:

  icecast:
    image: $IMAGE
    container_name: radio
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      ICECAST_SOURCE_PASSWORD: "${PASSWORD}"
      ICECAST_ADMIN_PASSWORD: "${PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"

  radio:
    image: liquisoap
    build: .
    container_name: radio-liquisoap
    restart: unless-stopped
    command: ["./radio.liq"]
    ports:
      - $PORT_LIQUIDSOAP:8000
    environment:
      VIRTUAL_HOST: "${DOMAIN_LIQ}"
      LETSENCRYPT_HOST: "${DOMAIN_LIQ}"
      ICECAST_SOURCE_PASSWORD: "${PASSWORD}"
    depends_on:
      - icecast
    volumes:
      - $MEDIA_DIR:/media:ro

networks:
  default:
    name: pegaz
