version: "3.7"

services:

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:10.0.2-ce.0
    restart: always
    hostname: "git.${DOMAIN}"
    ports:
      - '50022:22'
    volumes:
      - "${PATH_DATA}/gitlab/config:/etc/gitlab"
      - "${PATH_DATA}/gitlab/logs:/var/log/gitlab"
      - "${PATH_DATA}/gitlab/data:/var/opt/gitlab"
      - "${PATH_DATA}/gitlab/secret:/secret/gitlab/backups"
      - "/etc/letsencrypt:/etc/letsencrypt"
    environment:
      VIRTUAL_PORT:     80
      VIRTUAL_HOST:     "git.${DOMAIN}"
      LETSENCRYPT_HOST: "git.${DOMAIN}"
      LETSENCRYPT_EMAIL: $EMAIL

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4

networks:

  default:
    external: true
    name: pegaz
