version: "3.7"
services:

  plausible:
    image: $IMAGE
    container_name: plausible
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible-events-db
      - plausible-db
    ports:
      - $PORT:$PORT_EXPOSED
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      DATABASE_URL: "postgres://${USERNAME}:${PASSWORD}@plausible-db/plausible"
      CLICKHOUSE_DATABASE_URL: "http://plausible-events-db:8123/plausible-events-db"
      DISABLE_REGISTRATION: "true"
      DISABLE_SUBSCRIPTION: "true"
      ADMIN_USER_NAME: "${USERNAME}"
      ADMIN_USER_EMAIL: "${EMAIL}"
      ADMIN_USER_PWD: "${PASSWORD}"
      BASE_URL: "https://${DOMAIN}"

  plausible-db:
    image: postgres:14
    container_name: plausible-db
    restart: unless-stopped
    ports:
      - $PORT_DB:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "plausible"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"

  plausible-events-db:
    image: clickhouse/clickhouse-server:21.12-alpine
    container_name: plausible-events-db
    restart: unless-stopped
    volumes:
      - db-events:/var/lib/clickhouse
    tmpfs:
      - /var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  db:
  db-events:

networks:
  default:
    name: pegaz
