SETUP_WWW_REDIRECTION() {
  local PATH_FILE_REDIRECTION="$PATH_APPS/proxy/$FILENAME_REDIRECTION"
  
  # Créer le fichier si inexistant
  [[ ! -f "$PATH_FILE_REDIRECTION" ]] && touch "$PATH_FILE_REDIRECTION"
  
  # Supprimer l'ancienne redirection www si elle existe
  sed -i '/# Default www to domain redirection/,/#autogenerated/{/# Default www to domain redirection/!d}' "$PATH_FILE_REDIRECTION"
  sed -i '/# Default www to domain redirection/d' "$PATH_FILE_REDIRECTION"
  
  # Ajouter la redirection www au début du fichier
  local temp_file=$(mktemp)
  {
    echo "# Default www to domain redirection"
    echo "server {"
    echo "  server_name ~^www\.(.+)$;"
    echo "  return 301 https://\$1\$request_uri;"
    echo "}"
    echo "#autogenerated"
    echo ""
    cat "$PATH_FILE_REDIRECTION"
  } > "$temp_file"
  
  mv "$temp_file" "$PATH_FILE_REDIRECTION"
  
  echo "[INFO] Redirection www vers domaine principal configurée"
}
