SETUP_REDIRECTIONS() {
  local REDIRECTIONS=""
  SOURCE_APP "$1"

  # Si aucune redirection, ne rien faire
  [[ -z "$REDIRECTIONS" ]] && return

  local PATH_FILE_REDIRECTION="$PATH_APPS/proxy/$FILENAME_REDIRECTION"
  local PATH_FILE_NGINX="$PATH_APPS/$1/$FILENAME_NGINX"

  # Créer les fichiers si inexistants
  [[ ! -f "$PATH_FILE_NGINX" ]] && touch "$PATH_FILE_NGINX"
  [[ ! -f "$PATH_FILE_REDIRECTION" ]] && touch "$PATH_FILE_REDIRECTION"

  # Supprimer les anciennes lignes auto-générées
  REMOVE_LINE "$AUTOGENERATED_STAMP" "$PATH_FILE_NGINX"
  REMOVE_LINE "$AUTOGENERATED_STAMP" "$PATH_FILE_REDIRECTION"

  for REDIRECTION in $REDIRECTIONS; do
    local FROM=${REDIRECTION%->*}
    local TO=${REDIRECTION#*->}

    TYPE_FROM=$(REDIRECTION_TYPE "$FROM")
    TYPE_TO=$(REDIRECTION_TYPE "$TO")

    if [[ $TYPE_FROM == "route" ]]; then
      # /route->/route
      [[ $TYPE_TO == "route" ]] && echo "rewrite ^$FROM$ https://$DOMAIN$TO permanent; $AUTOGENERATED_STAMP" >> "$PATH_FILE_NGINX"
      # /route->url
      [[ $TYPE_TO == "url" || $TYPE_TO == "domain" ]] && echo "rewrite ^$FROM$ $TO permanent; $AUTOGENERATED_STAMP" >> "$PATH_FILE_NGINX"
      # domain->url/route/domain
    elif [[ $TYPE_FROM == "domain" ]]; then
      {
        echo "server {"
        echo "  server_name $FROM;"
        [[ $TYPE_TO == "route" ]] && echo "  return 301 https://$DOMAIN$TO;"
        [[ $TYPE_TO == "url" || $TYPE_TO == "domain" ]] && echo "  return 301 $TO;"
        echo "}"
        echo "$AUTOGENERATED_STAMP"
      } >> "$PATH_FILE_REDIRECTION"
    fi
  done
}
