SOURCE_APP() {
  [[ -f "$PATH_DOCKERWEB_APPS/$1/$FILENAME_CONFIG" ]] && source "$PATH_DOCKERWEB_APPS/$1/$FILENAME_CONFIG"
  [[ -f "$PATH_DOCKERWEB_APPS/$1/$FILENAME_ENV" ]] && source "$PATH_DOCKERWEB_APPS/$1/$FILENAME_ENV"
}
