SOURCE_SERVICE() {
  [[ -f "$PATH_DOCKERWEB_SERVICES/$1/$FILENAME_CONFIG" ]] && source "$PATH_DOCKERWEB_SERVICES/$1/$FILENAME_CONFIG"
  [[ -f "$PATH_DOCKERWEB_SERVICES/$1/$FILENAME_ENV" ]] && source "$PATH_DOCKERWEB_SERVICES/$1/$FILENAME_ENV"
}
