version: "3.7"
services:

  gitea:
    image: $IMAGE
    container_name: gitea
    restart: unless-stopped
    depends_on:
      - gitea-db
    ports:
      - $PORT:$PORT_EXPOSED
      - "127.0.0.1:${PORT_SSH}:22"
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    environment:
      VIRTUAL_PORT: "${PORT}"
      VIRTUAL_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      ROOT_URL: "http://${SUBDOMAIN}.${DOMAIN}"
      BASE_URL: "http://${SUBDOMAIN}.${DOMAIN}"
      SSH_DOMAIN: "${SUBDOMAIN}.${DOMAIN}"
      DISABLE_REGISTRATION: "true"
      HTTP_PORT: "${PORT}"
      SSH_PORT: "${PORT_SSH}"
      USER_UID: "${GIT_UID}"
      USER_GID: "${GIT_GID}"
      GITEA__database__DB_TYPE: "postgres"
      GITEA__database__HOST: "gitea-db"
      GITEA__database__NAME: "gitea"
      GITEA__database__USER: "${USERNAME}"
      GITEA__database__PASSWD: "${PASSWORD}"

  gitea-db:
    image: postgres:alpine
    container_name: gitea-db
    restart: unless-stopped
    ports:
      - $PORT_DB:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "gitea"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"

volumes:
  data:
  db:

networks:
  default:
    external:
      name: pegaz
