version: "3.8"
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: "${MAILSERVER_DOMAIN}"
    env_file: mailserver.env
    restart: unless-stopped
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
    volumes:
      - data:/var/mail/
      - state:/var/mail-state/
      - logs:/var/log/mail/
      - config:/tmp/docker-mailserver/
      - certs:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    environment:
      ENABLE_SPAMASSASSIN: 1
      SPAMASSASSIN_SPAM_TO_INBOX: 1
      ENABLE_CLAMAV: 1
      ENABLE_POSTGREY: 1
      ENABLE_FAIL2BAN: 0
      ENABLE_SASLAUTHD: 0
      ONE_DIR: 1
      TZ: "Europe/Paris"

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - "${MEDIA_DIR}:/media"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

volumes:
  data:
  state:
  logs:
  config:
  certs:

networks:
  default:
    name: pegaz
    external: true