version: "3.7"

services:
  icecast:
    container_name: icecast
    image: infiniteproject/icecast
    environment:
      - ICECAST_SOURCE_PASSWORD=${PASS}
      - ICECAST_ADMIN_PASSWORD=${PASS}
    restart: unless-stopped
  liquidsoap:
    container_name: liquidsoap
    image: phasecorex/liquidsoap
    command: ["./radio.liq"]
    environment:
      - ICECAST_SOURCE_PASSWORD=${PASS}
      - PUID=${PUID}
      - PGID=${PGID}
    depends_on:
      - icecast
    volumes:
      - ./radio.liq:/radio.liq:rw
      - ${PATH_MEDIA}/music:/music:ro
    restart: unless-stopped

networks:

  default:
    external: true
    name: pegaz
