services:

  nicotine:
    image: freddywullockx/nicotineplus
    container_name: nicotine
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - "${MEDIA_DIR}/download:/downloads"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      LOGIN: "${USERNAME}"
      PASSW: "${PASSWORD}"
      DARKMODE: "true"

networks:
  default:
    name: dockerweb
    external: true
