version: "3.7"
services:

  gitlab:
    image: $IMAGE
    container_name: gitlab
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
      - 22:22
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    environment:
      VIRTUAL_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = '${PASSWORD}'
        external_url '${SUBDOMAIN}.${DOMAIN}'
        nginx['listen_https'] = false

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    volumes:
      - ./config.toml:/etc/gitlab-runner/config.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  config:
  logs:
  data:

networks:
  default:
    external:
      name: pegaz
