#!/bin/bash
export SUBDOMAIN="cloud"
export PORT="7710"
export PORT_DB="7711"
export APPS_PRE_INSTALLED="calendar contacts mail notes music spreed extract metadata richdocuments richdocumentscode"
export APPS_ENABLED="files_external"
export APPS_DISABLED="activity photos recommendations dashboard"
export PHP_MEMORY_LIMIT="4G"
export PHP_UPLOAD_LIMIT="20G"
export PUID="www-data"
export PGID="www-data"
export REDIRECT="notes->/apps/notes cal->/apps/calendar contacts->/apps/contacts mail->/apps/mail /apps/files->/apps/files/?dir=/local"
