version: "3.7"
services:

  nextcloud:
    build: .
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    ports:
      - $PORT:8080
    volumes:
      - html:/var/www/html
      - data:/var/www/html/data
      - config:/var/www/html/config
      - apps:/var/www/html/apps
      - $DATA_DIR:/var/www/media
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      VIRTUAL_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_HOST: "${SUBDOMAIN}.${DOMAIN}"
      NEXTCLOUD_TRUSTED_DOMAINS: "${SUBDOMAIN}.${DOMAIN}"
      NEXTCLOUD_ADMIN_USER: "${USER}"
      NEXTCLOUD_ADMIN_PASSWORD: "${PASS}"
      NEXTCLOUD_ADMIN_EMAIL: "${EMAIL}"
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "${PASS}"
      POSTGRES_HOST: "nextcloud-db"
      REDIS_HOST: "nextcloud-redis"
      REDIS_HOST_PASSWORD: "${PASS}"
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      PHP_UPLOAD_LIMIT: "${PHP_UPLOAD_LIMIT}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      DATA_DIR: "${DATA_DIR}"

  nextcloud-db:
    image: postgres:alpine
    container_name: nextcloud-db
    restart: unless-stopped
    ports:
      - $PORT_DB:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "${USER}"
      POSTGRES_PASSWORD: "${PASS}"

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: redis-server --requirepass $PASS

volumes:
  db:
  html:
  data:
  config:
  apps:

networks:
  default:
    external:
      name: pegaz
