version: "3.7"
services:

  jellyfin:
    image: $IMAGE
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - config:/config
      - cache:/cache
      - $MEDIA_DIR:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      JELLYFIN_PublishedServerUrl: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

volumes:
  config:
  cache:

networks:
  default:
    external:
      name: pegaz
