version: "3.7"
services:

  proxy:
    image: nginxproxy/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - $PORT_HTTP:$PORT_HTTP
      - $PORT_HTTPS:$PORT_HTTPS
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTP_PORT: "${PORT_HTTP}"
      HTTPS_PORT: "${PORT_HTTPS}"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: proxy-acme
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
      DEFAULT_EMAIL: "${EMAIL}"
      DEBUG: "1"
      ACME_CA_URI: "${ACME_CA_URI}"
      ZEROSSL_API_KEY: "${ZEROSSL_API_KEY}"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    name: pegaz