version: "3.7"
services:

  proxy:
    image: $IMAGE
    container_name: proxy
    restart: unless-stopped
    ports:
      - $PORT_HTTP:$PORT_HTTP
      - $PORT_HTTPS:$PORT_HTTPS
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      HTTP_PORT: "${PORT_HTTP}"
      HTTPS_PORT: "${PORT_HTTPS}"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: proxy-acme
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
      DEFAULT_EMAIL: "${EMAIL}"

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

networks:
  default:
      name: pegaz
