services:

  proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - $PORT:$PORT
      - $PORT_HTTPS:$PORT_HTTPS
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/valere/docker-web/services/proxy/redirection.conf:/etc/nginx/conf.d/redirection.conf
      - /home/valere/docker-web/services/transmission/nginx.conf:/etc/nginx/vhost.d/transmission.domain.com_location
      - /home/valere/docker-web/services/nextcloud/nginx.conf:/etc/nginx/vhost.d/cloud.domain.com_location
      - /home/valere/docker-web/services/gitea/nginx.conf:/etc/nginx/vhost.d/git.domain.com_location
      - /home/valere/docker-web/services/drone/nginx.conf:/etc/nginx/vhost.d/drone.domain.com_location
      - /home/valere/docker-web/services/deluge/nginx.conf:/etc/nginx/vhost.d/deluge.domain.com_location
    environment:
      HTTP_PORT: "${PORT}"
      HTTPS_PORT: "${PORT_HTTPS}"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "5"

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: proxy-acme
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/valere/docker-web/services/proxy/redirection.conf:/etc/nginx/conf.d/redirection.conf
      - /home/valere/docker-web/services/transmission/nginx.conf:/etc/nginx/vhost.d/transmission.domain.com_location
      - /home/valere/docker-web/services/nextcloud/nginx.conf:/etc/nginx/vhost.d/cloud.domain.com_location
      - /home/valere/docker-web/services/gitea/nginx.conf:/etc/nginx/vhost.d/git.domain.com_location
      - /home/valere/docker-web/services/drone/nginx.conf:/etc/nginx/vhost.d/drone.domain.com_location
      - /home/valere/docker-web/services/deluge/nginx.conf:/etc/nginx/vhost.d/deluge.domain.com_location
    environment:
      NGINX_PROXY_CONTAINER: "proxy"
      DEFAULT_EMAIL: "${EMAIL}"
      DEBUG: "1"
      # ACME_CA_URI: "${ACME_CA_URI}"
      # ZEROSSL_API_KEY: "${ZEROSSL_API_KEY}"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  default:
    name: dockerweb
