version: "3.7"
services:

  politepol:
    container_name: politepol
    build:
      context: .
    ports:
      - $PORT:$PORT
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      DB_NAME: "politepol"
      DB_USER: "${USERNAME}"
      DB_PASSWORD: "${PASSWORD}"
      DB_HOST: "dbpolitepol"
      DB_PORT: "${PORT_DB}"
      WEB_PORT: "${PORT}"
      TIME_ZONE: 'Europe\/Paris'
    depends_on:
      - 'dbpolitepol'
    command: ["./wait-for-it.sh", "dbpolitepol", "/bin/bash", "./start.sh"]

  dbpolitepol:
    image: mysql:5.7
    container_name: dbpolitepol
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'politepol'
      MYSQL_USER: '${USERNAME}'
      MYSQL_PASSWORD: '${PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${PASSWORD}'
    ports:
      - $PORT_DB:3306
    volumes:
      - politepol:/var/lib/mysql

volumes:
  politepol:

networks:
  default:
    name: pegaz
