version: "3.7"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    environment:
      PUID: $PUID
      PGID: $PGID
      VIRTUAL_HOST:     "jelly.${DOMAIN}"
      LETSENCRYPT_HOST: "jelly.${DOMAIN}"
      JELLYFIN_PublishedServerUrl: "jelly.${DOMAIN}"
    volumes:
      - ${PATH_DATA}/jellyfin/config:/config
      - ${PATH_DATA}/jellyfin/cache:/cache
      - ${PATH_MEDIA}:/media
    devices:
      # - /dev/dri/renderD128:/dev/dri/renderD128 # only if graphic cards are available
      - /dev/dri/card0:/dev/dri/card0

networks:

  default:
    external: true
    name: pegaz
