WWW_REDIRECT() {
  local PATH_FILE_REDIRECTION="$PATH_APPS/proxy/$FILENAME_REDIRECTION"
  
  case $1 in
    "enable")
      echo "[INFO] Activation de la redirection www vers le domaine principal..."
      SETUP_WWW_REDIRECTION
      EXECUTE "restart proxy" ""
      echo "[✓] Redirection www activée"
      ;;
    "disable")
      echo "[INFO] Désactivation de la redirection www..."
      if [[ -f "$PATH_FILE_REDIRECTION" ]]; then
        sed -i '/# Default www to domain redirection/,/#autogenerated/d' "$PATH_FILE_REDIRECTION"
        EXECUTE "restart proxy" ""
        echo "[✓] Redirection www désactivée"
      else
        echo "[!] Aucune redirection www trouvée"
      fi
      ;;
    "status")
      if grep -q "# Default www to domain redirection" "$PATH_FILE_REDIRECTION" 2>/dev/null; then
        echo "[✓] Redirection www activée"
      else
        echo "[!] Redirection www désactivée"
      fi
      ;;
    *)
      echo "Usage: docker-web www-redirect [enable|disable|status]"
      echo ""
      echo "Commands:"
      echo "  enable   - Active la redirection www.domain.com -> domain.com"
      echo "  disable  - Désactive la redirection www"
      echo "  status   - Affiche le statut de la redirection www"
      ;;
  esac
}

# Alias pour la commande avec tiret
WWW-REDIRECT() {
  WWW_REDIRECT "$@"
}
