services:

  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - "${MEDIA_DIR}:/mnt/media"
    depends_on:
      umami-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl ${DOMAIN}/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      DATABASE_URL: "postgresql://${USERNAME}:${PASSWORD}@umami-db/umami"
      DATABASE_TYPE: postgresql
      APP_SECRET: "${PASSWORD}"
  umami-db:
    image: postgres:15-alpine
    container_name: umami-db
    ports:
      - $PORT_DB:5432
    environment:
      POSTGRES_DB: "umami"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:

networks:
  default:
    name: dockerweb
    external: true
