version: "3.7"
services:

  antmediaserver:
    image: nibrev/ant-media-server
    container_name: antmediaserver
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - "${MEDIA_DIR}:/media"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

networks:
  default:
    name: pegaz
