version: "3.7"
services:

  deluge:
    image: $IMAGE
    container_name: deluge
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - config:/config
      - ./images:/usr/lib/python3.10/site-packages/deluge/ui/web/images
      - "${MEDIA_DIR}/download:/downloads"
      - "${MEDIA_DIR}/download:/watch"
      - "${MEDIA_DIR}:/media"
    environment:
      VIRTUAL_PORT: "${PORT}"
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

volumes:
  config:

networks:
  default:
    name: pegaz
