services:

  deluge:
    image: linuxserver/deluge:2.1.1
    container_name: deluge
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - config:/config
      - "${MEDIA_DIR}/download:/downloads"
      - "${MEDIA_DIR}/download:/watch"
      - "${MEDIA_DIR}:/media"
    environment:
      VIRTUAL_PORT: "${PORT}"
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

volumes:
  config:

networks:
  default:
    name: pegaz
    external: true
