version: "3.7"
services:

  deluge:
    image: $IMAGE
    container_name: deluge
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - config:/config
      - ${DATA_DIR}:/media
    environment:
      VIRTUAL_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_HOST: "${SUBDOMAIN}.${DOMAIN}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      PUID: "${PUID}"
      PGID: "${PGID}"
      FILE__PASSWORD: "${PATH_PEGAZ}/pegazsecret"

volumes:
  config:

networks:
  default:
    external:
      name: pegaz
