version: "3.7"
services:

  deluge:
    image: $IMAGE
    container_name: deluge
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - config:/config
      - "${MEDIA_DIR}/downloads:/downloads"
      - "${MEDIA_DIR}/downloads:/watch"
    environment:
      VIRTUAL_PORT: "${PORT}"
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      LETSENCRYPT_EMAIL: "${EMAIL}"
      PUID: "${PUID}"
      PGID: "${PGID}"

volumes:
  config:

networks:
  default:
    external:
      name: pegaz
