version: "3.8"
services:

  __SERVICE_NAME__:
    image: nginx:1.23.2-alpine
    container_name: __SERVICE_NAME__
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - "${MEDIA_DIR}:/media"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

networks:
  default:
    name: pegaz
    external: true
