services:
  penpot:
    image: penpotapp/frontend:$VERSION
    container_name: penpot
    restart: always
    depends_on:
      - penpot-backend
      - penpot-exporter
    ports:
      - $PORT:$PORT_EXPOSED
    volumes:
      - assets:/opt/data
    env_file:
      - config.env
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PENPOT_PUBLIC_URI: $DOMAIN
      PENPOT_HTTP_SERVER_HOST: "0.0.0.0"
      PENPOT_DATABASE_USERNAME: "${USERNAME}"
      PENPOT_DATABASE_PASSWORD: "${PASSWORD}"

  penpot-backend:
    image: penpotapp/backend:$VERSION
    container_name: penpot-backend
    restart: always
    depends_on:
      - penpot-db
      - penpot-redis
    volumes:
      - assets:/opt/data
    env_file:
      - config.env
    environment:
      PENPOT_DATABASE_USERNAME: "${USERNAME}"
      PENPOT_DATABASE_PASSWORD: "${PASSWORD}"
      PENPOT_SMTP_DEFAULT_FROM: "${EMAIL}"
      PENPOT_SMTP_DEFAULT_REPLY_TO: "${EMAIL}"

  penpot-exporter:
    image: penpotapp/exporter:$VERSION
    container_name: penpot-exporter
    env_file:
      - config.env
    environment:
      PENPOT_PUBLIC_URI: "http://penpot"
      PENPOT_DOMAIN_WHITE_LIST: "${DOMAIN}"

  penpot-db:
    image: postgres:14-alpine
    container_name: penpot-db
    restart: always
    stop_signal: SIGINT
    ports:
      - $PORT_DB:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_DB: "penpot"
      POSTGRES_USER: "${USERNAME}"
      POSTGRES_PASSWORD: "${PASSWORD}"

  penpot-redis:
    image: redis:alpine3.16
    container_name: penpot-redis
    restart: always

volumes:
  db:
  assets:

networks:
  default:
    name: dockerweb
    external: true
