services:

  joal:
    image: anthonyraymond/joal
    container_name: joal
    restart: unless-stopped
    ports:
      - $PORT:$PORT_EXPOSED
    command: ["--joal-conf=/data", "--spring.main.web-environment=true", "--server.port=$PORT_EXPOSED", "--joal.ui.path.prefix=NOSPECHAR", "--joal.ui.secret-token=$PASSWORD"]
    volumes:
      - "./config/torrents:/mnt/media"
      - ./config:/data
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

networks:
  default:
    name: dockerweb
    external: true
